In [2]:
import pandas as pd
import numpy as np

In [3]:
# Creating a dataframe from a 2D array
# You pass the list of columns

array_2d = np.array ([[1,2,3], [4,5,6], [7,8,9]])

pd.DataFrame(array_2d, columns = ['column 1', 'column 2', 'column 3'])

column 1  column 2  column 3
0         1         2         3
1         4         5         6
2         7         8         9

In [4]:
type(array_2d)

numpy.ndarray

In [5]:
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:

pd.DataFrame(array_2d, columns = ['column 1', 'column 2', 'column 3'])

column 1  column 2  column 3
0         1         2         3
1         4         5         6
2         7         8         9