In [2]:
import numpy as np

In [3]:
## Generating an identity array 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
x = np.identity(4)

In [5]:
type(x)

numpy.ndarray

In [8]:
## Generating an identity matrix of 1s
y = np.eye(4)

In [10]:
# You can multiply with any constant

y * 7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [11]:
x * 7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [12]:
# Generating zero array of a given size
# 1 dimensional zero array

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# Creating two dimensional array: pass the tuple of rows and columns' number
#np.zeros((rows, columns))

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
# Generating ones array of a given size
# 1 dimensional one array

np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
# Creating two dimensional ones array: pass the tuple of rows and columns' number
# np.ones((rows, columns))

np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
## Generating an array in a given range or interval

np.arange(0,5)

array([0, 1, 2, 3, 4])

In [18]:
print(np.arange(0,5))

[0 1 2 3 4]


In [19]:
## If you want to control the step size

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
## You can also use linspace to generate an evenly spaced numbers in a given interval

np.linspace(0,20,5)

In [22]:
print(np.linspace(0,20,5))

[ 0.  5. 10. 15. 20.]


In [23]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [25]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
## Generating an array with random values
# Create a 1D array with 4 random numbers

np.random.rand(4)

array([0.66938586, 0.77854491, 0.69808844, 0.07499944])

In [31]:
np.random.rand(2)

array([0.42284424, 0.55566809])

In [32]:
np.random.rand(4,5)

array([[0.7911484 , 0.95489756, 0.76513025, 0.87426335, 0.58259183],
       [0.75278166, 0.52992328, 0.815977  , 0.14818461, 0.15739745],
       [0.37402347, 0.00445295, 0.07104385, 0.93607785, 0.09170996],
       [0.52127705, 0.75571186, 0.48486602, 0.49752542, 0.10971927]])

In [33]:
### Generate one random integer in a given range

np.random.randint(5,50)

11

In [34]:
np.random.randint(1,10)

6

In [39]:
### Generate 10 random integers in a given range

np.random.randint(0,100,10)


array([24, 16, 36, 12, 28, 56, 30, 91, 46, 59])

In [50]:
## Random see to output the same random vaues at all run time 
import random

random.seed(10)

random.randint(5,50)

41

In [48]:
#different with above code
np.random.randint(5,50)

34